### PR TITLE
Fixed a new order of branches to be in the right format

### PR DESCRIPTION
**Pull request by cochabambinoski**
Had to edit a little thing in the readme and now everything is fine

### CODE REVIEW

**Comment by cochabambinoski** [comment]
I just want to mention that I have permissions to work alone in this project, thank you :)

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

### Hello team  🌟

**Very nice work on this project, however, the following changes need to be done before moving on ⬇️** 

- There is no link to sign in or sign up with Facebook in the live link, please fix that.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by cochabambinoski** [comment]
I am sorry, that is part of milestone-7 that I have not to do

**Review by Redvanisation — CHANGES_REQUESTED** [review]
# Changes required  ♻️ 

- In order for this milestone to be accepted the **Facebook login feature should be working online**, and for that to be tested or used there should be a **link to log in or sign up with Facebook** in the **live version of the project**, please implement that before asking for re-review.


### _After making the required changes please submit a new code review request_

### Good luck! 🍀

**Comment by cochabambinoski** [comment]
According to the new workflow for the Milestone project, Milestone-7 (that requires to implement login with Facebook account trough Omniauth) has been deprecated, which it means users don't have to do it anymore, and its not a requirement for the milestone-8, that ca be described here:
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/
image

**Review by Redvanisation — APPROVED** [review]
# Milestone approved ✔️ 

**- Milestone 7 has been recently set as deprecated and the rule isn't clear because it says you don't have to ask for a review for this milestone, but the milestone 9 made it clearer, you have met all the requirements.**

### You may merge it and submit a project completion form. 🚀 

### Good luck! 🍀

**Comment by cochabambinoski** [comment]
But milestone-9 is optional, not even deprecated

**Comment by cochabambinoski** [comment]
Finished

**Pull request merged**
