### PR TITLE
Finished the milestone 5

### PR DESCRIPTION
**Pull request by cochabambinoski**
Requirements completed

### CODE REVIEW

**Comment by cochabambinoski** [comment]
I just want to mention that I have permission to work alone in this project, thank you :)

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello @cochabambinoski 

Nice job !! Really gob job!!!
However, there are some requirements that are not met.

1. According to [that](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png), Posts timeline includes posts written by logged-in user and their friends.

2. The tests are [required](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png), but there are no integrations tests. Please, add them.

Kindly make the suggested changes and submit a new code review request.
Thanks

Mael FOSSO

**Comment by cochabambinoski** [comment]
Hey, according to the new milestone workflow, I should not do the milestone 3, where is the post listing, so I jumped to milestone 5, and I have just added the rspec tests.

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello @cochabambinoski 

> Hey, according to the new milestone workflow, I should not do the milestone 3, where is the post listing, so I jumped to milestone 5, and I have just added the rspec tests.

You're right about milestone 3. But what it's required is not related to Milestone 3 but Milestone 5. The fact is the posts a connected user see have to be either its own posts or its friends posts. Not all the posts. So please, fix it!

About the Spec, almost well done! However, it's not complete. 
1. What you wrote concern only **sending the friendship request**.  
- User 1 sign up, 
- User 2 sign up,
- User 2 look for User 1 in the list of Users and **Request him a friendship** 
There is no part concerning the acceptation of User 1.

2. When running the test, it should failed because of the **Request him a friendship** message, which is not supposed to be there at the time you describe be.  I didn't see that message anywhere (in your code). 

3. I check in your `Gemfile`, there is no **Capybara** gem. Please, add it. I suggest you take a look on this [article](https://thoughtbot.com/blog/rspec-integration-tests-with-capybara) about how to **Write integration test with RSpec and Capybara**.

Please, could you write a complete integration tests?

Kindly make the suggested changes and submit a new code review request.
Thanks

Mael FOSSO

**Comment by cochabambinoski** [comment]
oh, I didn't know that, I am going to make the changes required, thank you.

**Comment by cochabambinoski** [comment]
> # Changes required 
> Hello @cochabambinoski
> 
> > Hey, according to the new milestone workflow, I should not do the milestone 3, where is the post listing, so I jumped to milestone 5, and I have just added the rspec tests.
> 
> You're right about milestone 3. But what it's required is not related to Milestone 3 but Milestone 5. The fact is the posts a connected user see have to be either its own posts or its friends posts. Not all the posts. So please, fix it!
> 
> About the Spec, almost well done! However, it's not complete.
> 
> 1. What you wrote concern only **sending the friendship request**.
> 
> * User 1 sign up,
> * User 2 sign up,
> * User 2 look for User 1 in the list of Users and **Request him a friendship**
>   There is no part concerning the acceptation of User 1.
> 
> 1. When running the test, it should failed because of the **Request him a friendship** message, which is not supposed to be there at the time you describe be.  I didn't see that message anywhere (in your code).
> 2. I check in your `Gemfile`, there is no **Capybara** gem. Please, add it. I suggest you take a look on this [article](https://thoughtbot.com/blog/rspec-integration-tests-with-capybara) about how to **Write integration test with RSpec and Capybara**.
> 
> Please, could you write a complete integration tests?
> 
> Kindly make the suggested changes and submit a new code review request.
> Thanks
> 
> Mael FOSSO

oh, I didn't know that, I am going to make the changes required, thank you.

**Review by wathigo — APPROVED** [review]
### Changes Approved :heavy_check_mark:  
Great work implementing all the requested changes!

**You may move on.**

**Good luck :four_leaf_clover: 
Simon Wathigo**

**Pull request merged**
